import {
  avgSpeed,
  getDriverId,
  getTripId,
  getTimestamp,
  complaintLabel,
} from "./csv.js";

// Compute all the numbers the report needs.
export function computeStats(complaints, results) {
  const analyzed = complaints
    .map((c) => ({ complaint: c, result: results[c.id] }))
    .filter((x) => x.result);

  const total = analyzed.length;
  const suspicious = analyzed.filter((x) => x.result.verdict === "SUSPICIOUS");
  const legitimate = analyzed.filter((x) => x.result.verdict === "LEGITIMATE");
  const inconclusive = analyzed.filter((x) => x.result.verdict === "INCONCLUSIVE");

  const pct = (n) => (total ? ((n / total) * 100).toFixed(1) : "0.0");

  // Drivers flagged for compliance review (deduped, with their incidents)
  const flaggedMap = {};
  for (const x of suspicious) {
    const id = getDriverId(x.complaint.telemetry);
    if (!flaggedMap[id]) flaggedMap[id] = [];
    flaggedMap[id].push(x);
  }
  const flaggedDrivers = Object.entries(flaggedMap).map(([id, items]) => ({
    driverId: id,
    incidents: items.length,
    trips: [...new Set(items.map((x) => getTripId(x.complaint.telemetry)))],
    complaints: [...new Set(items.map((x) => complaintLabel(x.complaint.telemetry)))],
  }));

  return {
    total,
    analyzed,
    suspicious,
    legitimate,
    inconclusive,
    counts: {
      compliance: suspicious.length,
      traffic: legitimate.length,
      inconclusive: inconclusive.length,
    },
    pct: {
      compliance: pct(suspicious.length),
      traffic: pct(legitimate.length),
      inconclusive: pct(inconclusive.length),
    },
    flaggedDrivers,
  };
}

function esc(s) {
  return String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

// Google-Docs-friendly HTML. When uploaded to Drive and converted, headings and
// tables carry over cleanly.
export function buildReportHtml(complaints, results, dateStr) {
  const s = computeStats(complaints, results);

  const rows = s.analyzed
    .map((x, i) => {
      const t = x.complaint.telemetry;
      const r = x.result;
      const color =
        r.verdict === "SUSPICIOUS"
          ? "#c0392b"
          : r.verdict === "LEGITIMATE"
          ? "#1e8449"
          : "#b9770e";
      return `<tr>
        <td>${i + 1}</td>
        <td>${esc(getTripId(t))}</td>
        <td>${esc(getDriverId(t))}</td>
        <td>${esc(getTimestamp(t))}</td>
        <td>${esc(avgSpeed(t))} km/h</td>
        <td>${esc(complaintLabel(t))}</td>
        <td>${esc(r.road || "N/A")}</td>
        <td style="color:${color};font-weight:bold;">${esc(r.verdict)}</td>
        <td>${esc(r.reason)}${
        r.flags?.length ? `<br/><em>Flags: ${esc(r.flags.join("; "))}</em>` : ""
      }</td>
      </tr>`;
    })
    .join("");

  const flaggedRows = s.flaggedDrivers.length
    ? s.flaggedDrivers
        .map(
          (d) => `<tr>
            <td><strong>${esc(d.driverId)}</strong></td>
            <td>${d.incidents}</td>
            <td>${esc(d.trips.join(", "))}</td>
            <td>${esc(d.complaints.join(", "))}</td>
          </tr>`
        )
        .join("")
    : `<tr><td colspan="4">No drivers flagged for compliance review.</td></tr>`;

  return `<!doctype html><html><head><meta charset="utf-8"/></head><body>
  <h1>Daily Stop Complaint Report</h1>
  <p><strong>${esc(dateStr)}</strong><br/>
  Bangkok Rideshare Operations &middot; generated by Stop Classifier</p>

  <h2>Summary</h2>
  <table border="1" cellpadding="6" cellspacing="0">
    <tr><td>Total complaints analyzed</td><td>${s.total}</td></tr>
    <tr><td>Suspicious (compliance)</td><td>${s.counts.compliance} (${s.pct.compliance}%)</td></tr>
    <tr><td>Legitimate (traffic)</td><td>${s.counts.traffic} (${s.pct.traffic}%)</td></tr>
    <tr><td>Inconclusive</td><td>${s.counts.inconclusive} (${s.pct.inconclusive}%)</td></tr>
  </table>

  <h2>Traffic vs Compliance Breakdown</h2>
  <table border="1" cellpadding="6" cellspacing="0">
    <tr><th>Category</th><th>Count</th><th>Percentage</th></tr>
    <tr><td>Traffic / legitimate</td><td>${s.counts.traffic}</td><td>${s.pct.traffic}%</td></tr>
    <tr><td>Compliance risk</td><td>${s.counts.compliance}</td><td>${s.pct.compliance}%</td></tr>
    <tr><td>Inconclusive</td><td>${s.counts.inconclusive}</td><td>${s.pct.inconclusive}%</td></tr>
  </table>

  <h2>All Complaints by Trip</h2>
  <table border="1" cellpadding="6" cellspacing="0">
    <tr>
      <th>#</th><th>Trip</th><th>Driver</th><th>Time</th><th>Avg Speed</th>
      <th>Customer Complaint</th><th>Road</th><th>Verdict</th><th>AI Assessment</th>
    </tr>
    ${rows}
  </table>

  <h2>Drivers Flagged for Manual Compliance Review</h2>
  <table border="1" cellpadding="6" cellspacing="0">
    <tr><th>Driver ID</th><th>Incidents</th><th>Trips</th><th>Customer Complaints</th></tr>
    ${flaggedRows}
  </table>

  <p><em>End of report.</em></p>
  </body></html>`;
}

// Plain-text version for .txt download / clipboard.
export function buildReportText(complaints, results, dateStr) {
  const s = computeStats(complaints, results);
  const bar = (p) => "█".repeat(Math.round(parseFloat(p) / 5));

  const tripLines = s.analyzed
    .map((x, i) => {
      const t = x.complaint.telemetry;
      const r = x.result;
      const mark =
        r.verdict === "SUSPICIOUS" ? "[!]" : r.verdict === "LEGITIMATE" ? "[ok]" : "[?]";
      return `${String(i + 1).padStart(2, " ")}. ${mark} ${r.verdict}  Trip ${getTripId(
        t
      )} | Driver ${getDriverId(t)} | ${getTimestamp(t)}
     Avg ${avgSpeed(t)} km/h | Complaint: ${complaintLabel(t)} | Road: ${r.road || "N/A"}
     Assessment: ${r.reason}${r.flags?.length ? `\n     Flags: ${r.flags.join("; ")}` : ""}`;
    })
    .join("\n\n");

  const flaggedLines = s.flaggedDrivers.length
    ? s.flaggedDrivers
        .map(
          (d, i) =>
            `${i + 1}. Driver ${d.driverId} — ${d.incidents} incident(s)\n   Trips: ${d.trips.join(
              ", "
            )}\n   Complaints: ${d.complaints.join(", ")}`
        )
        .join("\n\n")
    : "No drivers flagged for compliance review today.";

  return `DAILY STOP COMPLAINT REPORT
${dateStr}
Bangkok Rideshare Operations
${"=".repeat(60)}

SUMMARY
${"-".repeat(40)}
Total complaints analyzed : ${s.total}
Suspicious (compliance)   : ${s.counts.compliance} (${s.pct.compliance}%)
Legitimate (traffic)      : ${s.counts.traffic} (${s.pct.traffic}%)
Inconclusive              : ${s.counts.inconclusive} (${s.pct.inconclusive}%)

BREAKDOWN
${"-".repeat(40)}
Traffic      ${bar(s.pct.traffic)} ${s.pct.traffic}%
Compliance   ${bar(s.pct.compliance)} ${s.pct.compliance}%
Inconclusive ${bar(s.pct.inconclusive)} ${s.pct.inconclusive}%

ALL COMPLAINTS BY TRIP
${"-".repeat(40)}
${tripLines}

DRIVERS FLAGGED FOR MANUAL COMPLIANCE REVIEW
${"-".repeat(40)}
${flaggedLines}

${"=".repeat(60)}
End of report`;
}

export function downloadFile(content, filename, type = "text/plain") {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
